# Generated by Django 5.2.6 on 2025-11-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_view_book", "Can view book"),
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="published_date",
        ),
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="relationship_app.author",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(blank=True, to="relationship_app.book"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Librarian", "Librarian"),
                    ("Member", "Member"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
    ]
